# Generated by Django 4.2.5 on 2023-09-14 09:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_design_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 9, 14, 16, 12, 29, 360583), null=True, verbose_name='Дата'),
        ),
    ]
